### ISSUE TITLE
blocking call to load_verify_locations

### ISSUE THREAD

**Issue by penguintamer** [dcmeglio/homeassistant-waste_management#13]
Home Assistant version: 2024.10.4
homeassistant-waste_management version: 0.1.6

```
WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0xffff83639ed0>,) inside the event loop by custom integration 'waste_management' at custom_components/waste_management/sensor.py, line 75: client = WMClient(self.username, self.password) (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/dcmeglio/homeassistant-waste_management/issues

For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "/usr/local/bin/hass", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.12/site-packages/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1986, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/waste_management/sensor.py", line 46, in async_setup_entry
    add_entities(entities, True)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 510, in _async_schedule_add_entities_for_entry 
    task = self.config_entry.async_create_task(
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config_entries.py", line 1143, in async_create_task
    task = hass.async_create_task_internal(   
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 829, in async_create_task_internal
    task = create_eager_task(target, name=name, loop=self.loop)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 644, in async_add_entities
    await add_func(coros, entities, timeout)  
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 550, in _async_add_and_update_entities
    tasks = [create_eager_task(coro, loop=self.hass.loop) for coro in coros]
  File "/usr/local/lib/python3.12/site-packages/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False) 
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/waste_management/sensor.py", line 75, in async_update
    client = WMClient(self.username, self.password)
```

**Comment by johntdyer** [comment]
Tried fixing this by adding async await for the sensor.py but it didnt seem to work.  My python skills are limited at best but I think this needs to be fixed in the waste_management library itself and I am not sure how best to go about it.... @dcmeglio  is this on your radar to address at some point ?

**Comment by LiquidPT** [comment]
just wanted to chime in to say I'm still getting a similar error (with a slightly different callstack) on Home Assistant 2025.2.5 and homeassistant-waste_management version: 0.1.6

```
Logger: homeassistant.util.loop
Source: util/loop.py:137
First occurred: 11:49:52 AM (1 occurrences)
Last logged: 11:49:52 AM

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fdf95513bf0>, '/usr/local/lib/python3.13/site-packages/certifi/cacert.pem', None, None) inside the event loop by custom integration 'waste_management' at custom_components/waste_management/sensor.py, line 75: client = WMClient(self.username, self.password) (offender: /usr/local/lib/python3.13/ssl.py, line 717: context.load_verify_locations(cafile, capath, cadata)), please create a bug report at https://github.com/dcmeglio/homeassistant-waste_management/issues 

For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations 
Traceback (most recent call last): 
File "<frozen runpy>", line 198, in _run_module_as_main 
File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) 
File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) 
File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) 
File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete self.run_forever() 
File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever self._run_once() 
File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once handle._run() 
File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) 
File "/config/custom_components/waste_management/sensor.py", line 46, in async_setup_entry add_entities(entities, True) 
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 524, in _async_schedule_add_entities_for_entry task = self.config_entry.async_create_task( 
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1144, in async_create_task task = hass.async_create_task_internal( 
File "/usr/src/homeassistant/homeassistant/core.py", line 832, in async_create_task_internal task = create_eager_task(target, name=name, loop=self.loop) 
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) 
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 658, in async_add_entities await add_func(coros, entities, timeout) 
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 564, in _async_add_and_update_entities tasks = [create_eager_task(coro, loop=self.hass.loop) for coro in coros] 
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) 
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 738, in _async_add_entity await entity.async_device_update(warning=False) 
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update await self.async_update() 
File "/config/custom_components/waste_management/sensor.py", line 75, in async_update client = WMClient(self.username, self.password)
```
