### ISSUE TITLE
TypeError: 'WMClient' object is not callable

### ISSUE THREAD

**Issue by johntdyer** [dcmeglio/homeassistant-waste_management#14]
```
2024-12-08 10:54:55.537 INFO (MainThread) [homeassistant.components.sensor] Setting up waste_management.sensor
2024-12-08 10:54:58.436 ERROR (MainThread) [homeassistant.components.sensor] waste_management: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 737, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/waste_management/sensor.py", line 76, in async_update
    client = await self.hass.async_add_executor_job(WMClient(self.username, self.password))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'WMClient' object is not callable
2024-12-08 10:54:58.440 ERROR (MainThread) [homeassistant.components.sensor] waste_management: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 737, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/waste_management/sensor.py", line 76, in async_update
    client = await self.hass.async_add_executor_job(WMClient(self.username, self.password))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'WMClient' object is not callable
```

Core     - 2024.12.1
Supervisor                2024.11.4
OS                    - 14.0

**Comment by johntdyer** [comment]
@dcmeglio  should we consider this abandoned and possibly looking for adoption ?

**Comment by dcmeglio** [comment]
Yes. I no longer have waste management for my trash service so I can’t really provide any support for this.

**Comment by johntdyer** [comment]
I would be happy to at least try and adopt the repo / project but I would need you to grant me appropriate access to do things like accept MR's and manage actions for the both repo's for release tasks.  I could also fork it and you could deprecate and link to mine if that is better for you..

**Comment by ParagonDefect** [comment]
@johntdyer there might be a [bug](https://github.com/home-assistant/core/issues/127966) in your version of HomeAssistant that doesn't allow the python module to be loaded during startup. Depending on your sys.path, HomeAssistant will try to load the module during runtime when the sensor is added or updated, which is considered a [blocking operation](https://developers.home-assistant.io/docs/asyncio_blocking_operations#import_module).

As a workaround, I copied the waste_management python module from /config/deps/ to /config/custom_components/waste_management/

I then updated config_flow.py & sensor.py files to load the classes from component's location instead of relying on the larger python environment.

Change line 14 of sensor.py & line 17 of config_flow.py from:
`from waste_management import WMClient`

to:
`from .waste_management import WMClient`

Restart HomeAssistant.

I don't know how long this will work nor what versions are all affected but it's something.

**Comment by johntdyer** [comment]
@ParagonDefect  - ok, but I am running HassOS, so arent those libraries immutable docker layers and just going to reset on restart?

**Comment by ParagonDefect** [comment]
I haven't tested with HassOS, I use core inside docker alongside mosquito & zwavejs2mqtt.

If I get some free time this weekend, I will try to look at it in the HassOS version you posted above.

**Comment by dbell68** [comment]
I'm trying to get this working in my HA container, but it seems to be missing the client.py that implements the WMClient code (which can be seen in this other repo https://github.com/dcmeglio/waste_management/tree/master/waste_management). HA startup completes without error but all I see are an Update entity and a Pre-Release button. I would have expected to see an error about not being able to import WMClient.

UPDATE:
Holy crap - I think I got this working. I copied the Entities.py and client.py (from the repo linked above which seems to be a standalone implementation) into the custom_components/waste_management directory created by adding Waste Mgmt from HACS. Then I copied all the API constant entries into the existing const.py and in each of the config_flow.py and sensor.py changed the import line to be:

from .client import WMClient

and restarted HA.

After restart, went into HACS devices list, clicked Add Device, chose the Waste Mgmt integration and that restarted config flow, asked for username and password, then asked me to confirm address and the 3 types of services we have.

And now I have an entity for each of the 3 services that show next pickup date:

![Image](https://github.com/user-attachments/assets/93faf540-b65d-40c6-9e36-f18bf3369634)

**Comment by sgoffman** [comment]
Wow, that's great! Are you in a position to push those missing .py files to the HACS repo, or does a project owner need to do that?

**Comment by johntdyer** [comment]
Excited to hear you made some progress on this, but afraid its not entirely clear to me what you did in this part of your description

```
Then I copied all the API constant entries into the existing const.py and in each of the config_flow.py and sensor.py changed the import line to be:
```

Could you clarify ?

**Comment by johntdyer** [comment]
@dbell68  ^ 

Maybe an example of the updated files so we can get a Diff to illustrate the necessary changes

**Comment by dbell68** [comment]
@johntdyer 
Apologies for the delay.

I added all the entries from https://github.com/dcmeglio/waste_management/blob/master/waste_management/const.py under the existing entries in https://github.com/dcmeglio/homeassistant-waste_management/blob/master/custom_components/waste_management/const.py to make a single file /config/custom_components/waste_management/const.py that contains them all.


```
"""Constants for the Waste Management Pickup integration."""

DOMAIN = "waste_management"

CONF_ACCOUNT = "account"
CONF_SERVICES = "services"

REST_API_URL = "https://rest-api.wm.com/"

API_KEY_PAYMENT= "6ACAFBEEC54039F21716"
API_KEY_ROLLOFF= "5B1B5D23674B426465F0"
API_KEY_REPAIR= "6277FF29BB19666078AC"
API_KEY_AUTHENTICATION= "6277FF29BB19666078AC"
API_KEY_BALANCE_INVOICE= "615F2EFC82FF8BB2F864"
API_KEY_CUSTOMER_SERVICES= "1611D2AB8045EFB4D148"
API_KEY_USER_ACCOUNTS= "AABFF96D4542575160FC"
API_KEY_USER_REQUEST_SERVICE= "F1ADA754F65E546BFC97"
API_KEY_CHAT_LOGGED_IN= "2DC6C5B8146A1C281F96"
API_KEY_CHAT_LOGGED_IN_MOBILE= "306B8BA80546A3CE5DEC"
API_KEY_APPLE_PAY= "B8F7CE5A093141B1FFA2"
API_KEY_APPLE_PAY_SCHEDULED= "4E6D3BBDE553BE2807ED"
API_KEY_APPLE_PAY_AUTOPAY= "6CBA95B0A31A94C3C91C"
API_KEY_APPLE_PAY_PROCESS= "0A4031783CB69A4BC435"
API_KEY_BULK_AUTOPAY_PAPERLESS_ENROLL= "65D55CF6F9D38F50E02C"
API_KEY_SERVICE_CHANGE= "74DC8D4A7C565E51908E"
API_KEY_PAUSE_SERVICE= "74DC8D4A7C565E51908E"
API_KEY_ALERTS= "C861FBA520CDD18ADC8D"
API_KEY_INCIDENTS_BY_USER_ID= "6277FF29BB19666078AC"
API_KEY_EXTRA_PICKUP= "615F2EFC82FF8BB2F864"
API_KEY_BULK_PICKUP= "6277FF29BB19666078AC"
API_KEY_RECYCLING_PICKUP= "615F2EFC82FF8BB2F864"
API_KEY_HISTORY_VISUALS= "615F2EFC82FF8BB2F864"
API_KEY_PENDING_CHARGES= "615F2EFC82FF8BB2F864"
API_KEY_COMBINED_ORDER_HISTORY= "6277FF29BB19666078AC"
API_KEY_SURVEY= "6277FF29BB19666078AC"
API_KEY_HOLIDAYS_USER_BY_CUSTOMER_ID= "6277FF29BB19666078AC"
API_KEY_HOLIDAYS_USER_BY_ADDRESS= "6277FF29BB19666078AC"
API_KEY_CONTACT_INFO_USER_BY_CUSTOMER_ID= "6277FF29BB19666078AC"
API_KEY_CONTACT_INFO_USER_BY_ADDRESS= "6277FF29BB19666078AC"
API_KEY_USER_BILLING_DETAILS= "6277FF29BB19666078AC"
API_KEY_PAPERLESS_PREFERENCES= "6277FF29BB19666078AC"
API_KEY_TEXT_FOR_BULK= "65D55CF6F9D38F50E02C"
API_KEY_TEXT_FOR_ROLLOFF= "65D55CF6F9D38F50E02C"
API_KEY_TEXT_FOR_XPU= "65D55CF6F9D38F50E02C"
API_KEY_TEXT_FOR_CONTAINER_REPAIR= "65D55CF6F9D38F50E02C"
API_KEY_REPORT_MISSED_PICKUP= "6277FF29BB19666078AC"
API_KEY_TEXT_FOR_CITY_BILLED_BULK= "65D55CF6F9D38F50E02C"
API_KEY_REFRESH_TOKEN= "0zqoBUUwHpGwp04xxkwM5zKBCy8SeLYm9BibvwEgN2g"
API_KEY_ORDERS= "E5E2902D4E578F37CNQ3"
```

**Comment by johntdyer** [comment]
@dbell68  

so I did the following with no success

Downloaded client.py & Entities.py
```
wget https://raw.githubusercontent.com/dcmeglio/waste_management/refs/heads/master/waste_management/client.py
 wget https://raw.githubusercontent.com/dcmeglio/waste_management/refs/heads/master/waste_management/Entities.py
```

edited

/config/custom_components/waste_management/sensor.py
/config/custom_components/waste_management/config_flow.py

and changed the following

```diff
- from waste_management import WMClient
+ from .client import WMClient
```

and then made the following changes to const.py

```diff
"""Constants for the Waste Management Pickup integration."""

DOMAIN = "waste_management"

CONF_ACCOUNT = "account"
CONF_SERVICES = "services"


+ REST_API_URL = "https://rest-api.wm.com/"
+ 
+ API_KEY_PAYMENT= "6ACAFBEEC54039F21716"
+ API_KEY_ROLLOFF= "5B1B5D23674B426465F0"
+ API_KEY_REPAIR= "6277FF29BB19666078AC"
+ API_KEY_AUTHENTICATION= "6277FF29BB19666078AC"
+ API_KEY_BALANCE_INVOICE= "615F2EFC82FF8BB2F864"
+ API_KEY_CUSTOMER_SERVICES= "1611D2AB8045EFB4D148"
+ API_KEY_USER_ACCOUNTS= "AABFF96D4542575160FC"
+ API_KEY_USER_REQUEST_SERVICE= "F1ADA754F65E546BFC97"
+ API_KEY_CHAT_LOGGED_IN= "2DC6C5B8146A1C281F96"
+ API_KEY_CHAT_LOGGED_IN_MOBILE= "306B8BA80546A3CE5DEC"
+ API_KEY_APPLE_PAY= "B8F7CE5A093141B1FFA2"
+ API_KEY_APPLE_PAY_SCHEDULED= "4E6D3BBDE553BE2807ED"
+ API_KEY_APPLE_PAY_AUTOPAY= "6CBA95B0A31A94C3C91C"
+ API_KEY_APPLE_PAY_PROCESS= "0A4031783CB69A4BC435"
+ API_KEY_BULK_AUTOPAY_PAPERLESS_ENROLL= "65D55CF6F9D38F50E02C"
+ API_KEY_SERVICE_CHANGE= "74DC8D4A7C565E51908E"
+ API_KEY_PAUSE_SERVICE= "74DC8D4A7C565E51908E"
+ API_KEY_ALERTS= "C861FBA520CDD18ADC8D"
+ API_KEY_INCIDENTS_BY_USER_ID= "6277FF29BB19666078AC"
+ API_KEY_EXTRA_PICKUP= "615F2EFC82FF8BB2F864"
+ API_KEY_BULK_PICKUP= "6277FF29BB19666078AC"
+ API_KEY_RECYCLING_PICKUP= "615F2EFC82FF8BB2F864"
+ API_KEY_HISTORY_VISUALS= "615F2EFC82FF8BB2F864"
+ API_KEY_PENDING_CHARGES= "615F2EFC82FF8BB2F864"
+ API_KEY_COMBINED_ORDER_HISTORY= "6277FF29BB19666078AC"
+ API_KEY_SURVEY= "6277FF29BB19666078AC"
+ API_KEY_HOLIDAYS_USER_BY_CUSTOMER_ID= "6277FF29BB19666078AC"
+ API_KEY_HOLIDAYS_USER_BY_ADDRESS= "6277FF29BB19666078AC"
+ API_KEY_CONTACT_INFO_USER_BY_CUSTOMER_ID= "6277FF29BB19666078AC"
+ API_KEY_CONTACT_INFO_USER_BY_ADDRESS= "6277FF29BB19666078AC"
+ API_KEY_USER_BILLING_DETAILS= "6277FF29BB19666078AC"
+ API_KEY_PAPERLESS_PREFERENCES= "6277FF29BB19666078AC"
+ API_KEY_TEXT_FOR_BULK= "65D55CF6F9D38F50E02C"
+ API_KEY_TEXT_FOR_ROLLOFF= "65D55CF6F9D38F50E02C"
+ API_KEY_TEXT_FOR_XPU= "65D55CF6F9D38F50E02C"
+ API_KEY_TEXT_FOR_CONTAINER_REPAIR= "65D55CF6F9D38F50E02C"
+ API_KEY_REPORT_MISSED_PICKUP= "6277FF29BB19666078AC"
+ API_KEY_TEXT_FOR_CITY_BILLED_BULK= "65D55CF6F9D38F50E02C"
+ API_KEY_REFRESH_TOKEN= "0zqoBUUwHpGwp04xxkwM5zKBCy8SeLYm9BibvwEgN2g"
+ API_KEY_ORDERS= "E5E2902D4E578F37CNQ3"

```

and I still end up w/ the following error

```
2025-06-26 11:09:55.773 INFO (MainThread) [homeassistant.components.sensor] Setting up waste_management.sensor
2025-06-26 11:09:58.569 ERROR (MainThread) [homeassistant.components.sensor] waste_management: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1304, in async_device_update
    await self.async_update()
  File "/config/custom_components/waste_management/sensor.py", line 79, in async_update
    client = await self.hass.async_add_executor_job(WMClient(self.username, self.password))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'WMClient' object is not callable
2025-06-26 11:09:58.576 ERROR (MainThread) [homeassistant.components.sensor] waste_management: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1304, in async_device_update
    await self.async_update()
  File "/config/custom_components/waste_management/sensor.py", line 79, in async_update
    client = await self.hass.async_add_executor_job(WMClient(self.username, self.password))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'WMClient' object is not callable
```

**Comment by dbell68** [comment]
Sorry for asking obvious but you put the two downloaded files in config/custom_components/waste_management and the permissions are such that they can be read by the account under which HA is running ?

The error suggests it is not able to find the WMClient class definition in the client.py file.

**Comment by johntdyer** [comment]
@dbell68  - Correct

```
➜  custom_components cd waste_management
➜  waste_management ls -la
total 64
drwxr-xr-x    4 root     root          4096 Jun 26 11:12 .
drwxr-xr-x  148 root     root          4096 Jun 26 10:15 ..
-rw-r--r--    1 root     root           604 Jun 26 10:21 Entities.py
-rw-r--r--    1 root     root           891 Feb 21  2023 __init__.py
drwxr-xr-x    2 root     root          4096 Jun 26 10:42 __pycache__
-rw-r--r--    1 root     root         13644 Jun 26 10:21 client.py
-rw-r--r--    1 root     root          4867 Jun 26 10:40 config_flow.py
-rw-r--r--    1 root     root          2189 Jun 26 10:14 const.py
-rw-r--r--    1 root     root           497 Feb 21  2023 manifest.json
-rw-r--r--    1 root     root          3236 Jun 26 10:40 sensor.py
-rw-r--r--    1 root     root           528 Feb 21  2023 strings.json
drwxr-xr-x    2 root     root          4096 Feb 21  2023 translations
➜  waste_management
```

**Comment by dbell68** [comment]
One other thing which surprised me.

Once I had added the WM integration from HACS, modified the files as described, and then restarted HA, I had to go to Integrations and click add integration and then choose the WM integration and it started the config flow. I was not expecting that second stage of setup.

Have you done that step or are you not able to get that far ?

Regards,
David
________________________________

**Comment by johntdyer** [comment]
Just tested this, went through the workflow, no difference at all... would you mind tar'ing up your wm directory within custom components so I can diff it file by file to see if I can maybe spot the difference?
